app:
  build: ./tile-server
  restart: always
  command: newrelic-admin run-program gunicorn wsgi:application -b 0.0.0.0:8080 -w 3
  ports:
    - "8080"
  links:
    - db:db
    - memcache:memcache
  volumes_from:
    - data

data:
  build: ./data
  volumes:
    - data
    - $HOME/nepal-tiles:/local_data

dbdata:
  image: kartoza/postgis
  volumes:
    - /var/lib/postgresql
  command: true

backupdb:
  image: kartoza/postgis
  command: true
  links:
    - db:db
  volumes:
    - $HOME/nepal-tiles:/backup
  environment:
    - PGHOST=db
    - PGDATABASE=gis
    - PGUSER=docker
    - PGPASSWORD=docker

redis:
  image: redis
  ports:
    - "6379"

haproxy:
  image: tutum/haproxy
  links:
    - app
  environment:
    - BACKEND_PORT=8080

nginx:
  build: ./nginx
  ports:
    - 80:80
  links:
    - haproxy

db:
  image: kartoza/postgis
  ports:
    - 25432:5432
  volumes_from:
    - dbdata

memcache:
  image: memcached
